max_report_age: false

ignore:
  - "app/**"

ignore:
  - "app/**"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  disable: false

coverage:
  status:
    project:
      default:
        target: 95%
        informational: false
    patch:
      default:
        target: 95%
        informational: false
